### ISSUE TITLE
Throw Customer Error to say people are on the wrong network

### ISSUE THREAD

**Issue by Bschuster3434** [Bschuster3434/fweb3_holder_matic_faucet#17]
When the user is connected to the wrong network, they will get this error:

`call revert exception (method="getBalance()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)`

This can be recreated by switching to a network that does not have the faucet.

We should throw an error that they are on the wrong network.

**Comment by archae0pteryx** [comment]
The new PR will at least tell them when they click the faucet. Should it be before or does that matter do you think?

**Comment by slinlee** [comment]
FYI, I get the above error when clicking on 'connect metamask' if I'm connected to the wrong network. The faucet button doesn't appear.

I'm just starting to explore the code, but maybe I can take a look at this today?

**Comment by archae0pteryx** [comment]
fixed with https://github.com/Bschuster3434/fweb3_holder_matic_faucet/pull/27
