### ISSUE TITLE
Error messages hang around after they're resolved

### ISSUE THREAD

**Issue by slinlee** [Bschuster3434/fweb3_holder_matic_faucet#20]
To reproduce:
- try connecting metamask with a different network (like Mumbai test net)
- Notice the error for "getBalance() doesn't exist"
- Toggle MetaMask to use the correct network (Polygon Mainnet)
- See that it properly connects but still shows the error

![image](https://user-images.githubusercontent.com/1197406/154171468-91d5df46-f02f-4456-8ee2-f1b48aece080.png)

Suggestion:
- MetaMask's docs recommend refreshing the page when a change in the network or chain is detected.

**Comment by archae0pteryx** [comment]
This should be taken care of in https://github.com/Bschuster3434/fweb3_holder_matic_faucet/pull/27
