### ISSUE TITLE
Add directions and links to add custom tokens to MM

### ISSUE THREAD

**Issue by archae0pteryx** [Bschuster3434/fweb3_holder_matic_faucet#22]
It would be nice if a sender of fWeb3 can point the reciever to directions on how to enable it in their wallet as well as other useful links. @slavingia does fweb3.xyz have an instructions page at all or should we do it faucet side?

**Comment by Bschuster3434** [comment]
@archae0pteryx I think you added this to the wrong board. Try here: https://github.com/slavingia/fweb3.xyz/issues
